Repository cloudfoundry/uaa, pull requests merged in 2018-03, with the labels that each got.

#784 Test for PR 781
  model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaStringUtilsTest.java
Labels: unscheduled

#781 Escape the correct regex characters
  model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java
Labels: unscheduled

#687 route all errors not explicitly mapped to the sad cloud error page to hide tomcat server information
  uaa/src/main/webapp/WEB-INF/web.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/ErrorRoutingIT.java
Labels: in progress

#769 resolve lower hostnames only
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilter.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilterTests.java
Labels: in progress

#747 Add input validation for az_attr
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/CheckTokenEndpointIntegrationTests.java
Labels: scheduled

#795 fix typo
  docs/UAA-Overview.rst
Labels: unscheduled
