Repository cloudfoundry/uaa, pull requests merged in 2018-06, with the labels that each got.

#822 update guava
  shared_versions.gradle
Labels: scheduled

#829 update bc
  server/src/test/java/org/cloudfoundry/identity/uaa/util/KeyWithCertTest.java
  shared_versions.gradle
Labels: scheduled

#831 update thymeleaf because of groovy
  shared_versions.gradle
Labels: scheduled

#844 Update-UAA-Tokens.md
  docs/UAA-Tokens.md
Labels: unscheduled

#821 spring updates
  shared_versions.gradle
Labels: scheduled

#825 update spring security
  shared_versions.gradle
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/RefreshTokenSupportIntegrationTests.java
Labels: scheduled

#832 update hibernate
  server/build.gradle
  shared_versions.gradle
Labels: in progress

#850 update jackson
  shared_versions.gradle
Labels: unscheduled

#857 Spring updates
  shared_versions.gradle
Labels: unscheduled
