Repository cloudfoundry/uaa, pull requests merged in 2019-08, with the labels that each got.

#971 update ldap model
  shared_versions.gradle
Labels: in progress

#1078 Features/change startup behavior 165798297
  build.gradle
  scripts/cargo/tomcat-conf/context.xml
  server/build.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/web/RecognizeFailureDispatcherServlet.java
  server/src/main/java/org/cloudfoundry/identity/uaa/web/tomcat/UaaStartupFailureListener.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/RecognizeFailureDispatcherServletTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/tomcat/UaaStartupFailureListenerTest.java
  uaa/src/main/webapp/WEB-INF/web.xml
Labels: scheduled

#1063 Remove powermock
  dependencies.gradle
  server/build.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/ClientAccessTokenValidity.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/ClientRefreshTokenValidity.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/TokenEndpointBuilder.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/TokenValidationService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/openid/IdTokenCreator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/refresh/RefreshTokenCreator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ChangeEmailEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/event/IdentityProviderEventPublisher.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/event/IdentityProviderModifiedEvent.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientAccessTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientRefreshTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/IntrospectEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenEndpointBuilderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenTestSupport.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/openid/IdTokenCreatorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ChangeEmailEndpointsMockMvcTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ChangeEmailEndpointsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/IdentityProviderModifiedEventTest.java
  uaa/src/main/webapp/WEB-INF/spring/login-server-security.xml
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
Labels: unscheduled

#1074 Package UAA WAR using the Spring Boot plugin
  build.gradle
  dependencies.gradle
  statsd/build.gradle
  uaa/build.gradle
  uaa/src/main/java/org/cloudfoundry/identity/uaa/UaaBootApplication.java
Labels: scheduled
