Repository cloudfoundry/uaa, pull requests merged in 2020-12, with the labels that each got.

#1457 revcover pipeline tests
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Labels: unscheduled

#1461 SamlKeyRotationMockMvcTests setup of test refactored
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/JdbcAuditServiceTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/saml/SamlKeyRotationMockMvcTests.java
Labels: unscheduled

#1438 Allow SCIM filtering of users by their "external_id" attribute
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/SimpleSearchQueryConverter.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsTests.java
Labels: unscheduled

#1460 set default of http pool to 5 per route and 10 max.
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/RestTemplateConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaHttpRequestUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCacheTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfiguratorTest.java
Labels: unscheduled

#1465 ensure always use uaa as zone
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/JdbcUnsuccessfulLoginCountingAuditServiceTests.java
Labels: unscheduled

#1471 ensure test default
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
Labels: unscheduled

#1470 cleanup tomcat dependency
  build.gradle
  dependencies.gradle
Labels: in progress

#1475 Bump - spring boot 2.3.7 - framework 5.2.12
  dependencies.gradle
Labels: dependencies, unscheduled

#1479 Bump guava version 30.0
  dependencies.gradle
Labels: dependencies, unscheduled

#1478 dependency update
  dependencies.gradle
  server/build.gradle
  server/src/test/resources/messages.properties
Labels: dependencies, unscheduled

#1469 write exception message only
  server/src/main/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCache.java
Labels: unscheduled

#1474 Refactor fetch of tokenKeyUrl
  server/src/main/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCache.java
  server/src/main/java/org/cloudfoundry/identity/uaa/cache/UrlContentCache.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadataFetcher.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
Labels: performance, unscheduled
