Repository cloudfoundry/uaa, pull requests merged in 2020-10, with the labels that each got.

#1380 Ensure SQL parameters do not contain -'s
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/SimpleSearchQueryConverter.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/ScimSearchQueryConverterTests.java
Labels: in progress

#1418 Postgresql requires version bump
  dependencies.gradle
Labels: dependencies, unscheduled

#1420 sync
  dependencies.gradle
  k8s/go.mod
  k8s/go.sum
  k8s/templates/values/image.yml
Labels: unscheduled

#1419 update spring boot and dependent frameworks
  dependencies.gradle
Labels: dependencies, unscheduled

#1417 fix: exclude not needed and outdated bc ext library
  server/build.gradle
Labels: unscheduled

#1422 revert pr #1418
  dependencies.gradle
Labels: unscheduled

#1427 Switch statsd_exporter image to use the one from cloudfoundry dockerhub
  k8s/templates/values/_values.yml
Labels: unscheduled
