Repository cloudfoundry/uaa, pull requests merged in 2021-08, with the labels that each got.

#1617 Update Font-Awesome to 4.7.0
  uaa/src/main/webapp/resources/oss/stylesheets/pui-3.0.0/font-awesome/fontawesome-webfont.eot
  uaa/src/main/webapp/resources/oss/stylesheets/pui-3.0.0/font-awesome/fontawesome-webfont.svg
  uaa/src/main/webapp/resources/oss/stylesheets/pui-3.0.0/font-awesome/fontawesome-webfont.ttf
  uaa/src/main/webapp/resources/oss/stylesheets/pui-3.0.0/font-awesome/fontawesome-webfont.woff
  uaa/src/main/webapp/resources/oss/stylesheets/pui-3.0.0/font-awesome/fontawesome-webfont.woff2
  uaa/src/main/webapp/vendor/font-awesome/css/font-awesome.css
  uaa/src/main/webapp/vendor/font-awesome/css/font-awesome.min.css
  uaa/src/main/webapp/vendor/font-awesome/fonts/FontAwesome.otf
  uaa/src/main/webapp/vendor/font-awesome/fonts/fontawesome-webfont.eot
  uaa/src/main/webapp/vendor/font-awesome/fonts/fontawesome-webfont.svg
  uaa/src/main/webapp/vendor/font-awesome/fonts/fontawesome-webfont.ttf
  uaa/src/main/webapp/vendor/font-awesome/fonts/fontawesome-webfont.woff
Labels: dependencies, unscheduled

#1618 Update jQuery version to v3.6.0
  uaa/src/main/webapp/vendor/jquery/javascripts/jquery.js
Labels: dependencies, javascript, unscheduled

#1625 update activesupport 5.2.4.3
  uaa/slate/Gemfile.lock
Labels: dependencies, ruby, unscheduled

#1626 update kramdown 2.3.1
  uaa/slate/Gemfile.lock
Labels: dependencies, ruby, unscheduled

#1627 update gem dependencies
  uaa/slate/Gemfile.lock
Labels: dependencies, ruby, unscheduled

#1624 fix: Bug with Origin chooser and allowed providers
  server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
Labels: unscheduled

#1128 Do not expire invitations on GET requests
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/invitations/InvitationsController.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStoreTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/InMemoryExpiringCodeStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsControllerTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/InvitationsServiceMockMvcTests.java
Labels: feature proposal, in progress

#1630 fix error display
  server/src/main/java/org/cloudfoundry/identity/uaa/home/HomeController.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationFilter.java
  server/src/main/resources/templates/web/external_auth_error.html
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/OIDCLoginIT.java
Labels: unscheduled

#1646 Fix issue #1610
  uaa/slateCustomizations/source/index.html.md.erb
Labels: unscheduled, documentation

#1643 refactor passcode page and show copy to clipboard icon
  server/src/main/resources/templates/web/passcode.html
Labels: unscheduled

#1657 Bump Spring Dependencies
  dependencies.gradle
Labels: unscheduled, dependencies, java

#1629 refactorings from sonar scanner found
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
Labels: unscheduled

#1644 switch jaxb runtime
  dependencies.gradle
  server/build.gradle
  server/pom.xml
  uaa/build.gradle
  uaa/pom.xml
Labels: unscheduled, dependencies, java

#1614 Change and update mail library
  dependencies.gradle
  uaa/build.gradle
Labels: unscheduled, dependencies, java
