Repository cloudfoundry/uaa, pull requests merged in 2021-11, with the labels that each got.

#1685 Migration tests from JUnit4 to JUnit5 - first iteration
  server/src/test/java/org/cloudfoundry/identity/uaa/account/ResetPasswordAuthenticationEntryPointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/account/ResetPasswordAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/AuditEventTypeTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/LoggingAuditServiceTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/event/ApprovalModifiedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/event/EntityDeletedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/AuthzAuthenticationManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ChainedAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/CommonLoginPolicyTest.java
Labels: unscheduled

#1714 Clean up tests.
  server/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsControllerTest.java
Labels: unscheduled

#1709 JOSE Header must ignore all not understood parameters
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/HeaderParameters.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtHeaderHelperTest.java
Labels: unscheduled

#1712 Refactor test for issue #1710
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtHeaderHelperTest.java
Labels: unscheduled

#1717 Use golang 1.17
  k8s/go.mod
Labels: unscheduled

#1716 Fix error mapping /error
  server/src/main/java/org/cloudfoundry/identity/uaa/home/HomeController.java
  uaa/src/main/webapp/WEB-INF/spring-servlet.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/ErrorRoutingIT.java
Labels: unscheduled, bug

#1719 Add "FOR UPDATE SKIP LOCKED" DeleteExpiredQuery
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/PostgresLimitSqlAdapter.java
Labels: unscheduled

#1726 extend OIDC related documentation parts
  uaa/slateCustomizations/source/index.html.md.erb
  uaa/src/test/java/org/cloudfoundry/identity/uaa/logout/LogoutInfoEndpointDocs.java
Labels: documentation

#1731 Ensure that application/json is set as mediatype
  server/src/main/java/org/cloudfoundry/identity/uaa/web/ConvertingExceptionView.java
  server/src/test/java/org/cloudfoundry/identity/uaa/error/ConvertingExceptionViewTests.java
Labels: unscheduled
