Repository cloudfoundry/uaa, pull requests merged in 2021-01, with the labels that each got.

#1330 Update externalId on login
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/LdapLoginAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUser.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManagerTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/OIDCLoginIT.java
Labels: unscheduled

#1487 K8s templates now allow configuring `issuer.uri`
  k8s/templates/uaa.lib.yml
  k8s/templates/values/_values.yml
  k8s/test/config_map_test.go
Labels: unscheduled

#1486 fix issue #1447: bump velocity 2.2
  dependencies.gradle
  server/build.gradle
Labels: unscheduled

#1484 Bump - spring boot 2.4.1 - framework 5.3.2
  dependencies.gradle
  server/src/main/resources/spring/login-ui.xml
  server/src/main/resources/templates/web/invitations/accept_invite.html
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaUiRequiredFilterTests.java
  statsd-lib/build.gradle
  uaa/src/main/webapp/WEB-INF/spring/authentication.xml
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsMockMvcTests.java
Labels: dependencies, unscheduled

#1499 fix leftover from spring boot update
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/JdbcUnsuccessfulLoginCountingAuditServiceTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointDocs.java
Labels: unscheduled

#1500 Alphabetize dependencies.gradle
  dependencies.gradle
Labels: unscheduled

#1501 Bump - spring boot 2.4.2 - framework 5.3.3
  dependencies.gradle
Labels: unscheduled

#1462 Bump version spring oauth 2.5.0.RELEASE
  dependencies.gradle
  server/src/test/java/org/cloudfoundry/identity/uaa/login/util/RandomValueStringGenerator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/GeneralMfaProviderValidatorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/JdbcMfaProviderProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaCheckerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaProviderEndpointsTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsEndpointMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ForcePasswordChangeControllerMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TotpMfaEndpointMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/util/RandomValueStringGenerator.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/ldap/AbstractLdapMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/mfa_provider/MfaProviderEndpointsMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/AbstractTokenMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/PasswordResetEndpointMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsMockMvcTests.java
Labels: dependencies, unscheduled

#1503 use test class
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/mfa_provider/MfaProviderEndpointDocs.java
Labels: unscheduled

#1504 refactor: use old RandomValueStringGenerator for internal tests
  model/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaProviderTest.java
  model/src/test/java/org/cloudfoundry/identity/uaa/mfa/RandomValueStringGenerator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordResetEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/event/EntityDeletedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/JdbcClientMetadataProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/AutologinAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/TotpMfaEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientAccessTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientRefreshTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenRevocationEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/expression/IsSelfCheckTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/JdbcRevocableTokenProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfiguratorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ChangeEmailEndpointsMockMvcTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/TimeBasedExpiringValueMapTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaTokenUtilsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsServiceTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/IdentityProviderModifiedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/ServiceProviderModifiedEventTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/client/ClientMetadataAdminEndpointsMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/TotpMfaEndpointIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/InvitationsServiceMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/mfa_provider/MfaProviderEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenRevocationEndpointMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/DisableUserManagementSecurityFilterMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneSwitchingFilterMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/ZonesWriteScopeMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenEndpointMockMvcTest.java
Labels: unscheduled

#1505 refactor: use old RandomValueStringGenerator for doc classes
  uaa/src/test/java/org/cloudfoundry/identity/uaa/client/ClientMetadataAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AuthorizeEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/password/PasswordEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/UaaSamlIDPEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserInfoEndpointDocs.java
Labels: unscheduled

#1506 test robustness improved
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/AbstractTokenMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenEndpointMockMvcTest.java
Labels: unscheduled

#1497 Credentials in UsernamePasswordAuthenticationToken should be String
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ChainedAuthenticationManager.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ChainedAuthenticationManagerTest.java
Labels: unscheduled

#1509 prevent issues during pollution
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled

#1510 Bump bouncyCastleVersion from 1.67 to 1.68
  dependencies.gradle
Labels: dependencies

#1513 Update jQuery version to v3.5.1
  uaa/src/main/webapp/vendor/jquery/javascripts/jquery.js
Labels: dependencies, unscheduled
