Repository cloudfoundry/uaa, pull requests merged in 2021-12, with the labels that each got.

#1736 fix: read logoutUrl from yaml
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractExternalOAuthIdentityProviderDefinition.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
Labels: bug

#1744 exclude mina-core
  server/build.gradle
Labels: dependencies

#1745 change doc footer
  uaa/slateCustomizations/source/index.html.md.erb
Labels: unscheduled

#1750 Fix issue #1713
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_101_1639764160__Add_LowerIndex_To_Users_Wo_Origin.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_101_1639764160__Add_LowerIndex_To_Users_Wo_Origin.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_101_1639764160__Add_LowerIndex_To_Users_Wo_Origin.sql
Labels: accepted, performance

#1754 update library json
  dependencies.gradle
  server/build.gradle
Labels: dependencies, java

#1755 Use OAuth2 encoded authorization header for tests
  server/src/test/java/org/cloudfoundry/identity/uaa/test/UaaTestAccounts.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IntrospectEndpointIntegrationTests.java
Labels: unscheduled
