Repository cloudfoundry/uaa, pull requests merged in 2021-10, with the labels that each got.

#1689 Bump xmlsec library 1.5.8 to 2.2.3
  dependencies.gradle
  server/build.gradle
Labels: dependencies, java

#1669 Replace deprecated Mockito.verifyZeroInteractions on Mockito.verifyNoInteractions
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/BackwardsCompatibleTokenEndpointAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/CurrentUserCookieRequestFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/PasswordChangeRequiredFilterTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/PasswordChangeUiRequiredFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/SessionResetFilterTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/listener/AuthenticationSuccessListenerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/CommonLoginPolicyTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/ChangeEmailControllerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/ChangePasswordControllerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/TotpMfaEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaUiRequiredFilterTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/StatelessMfaAuthenticationFilterTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/ChainedSignatureVerifierTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadataFetcherTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/TokenValidationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/beans/BackwardsCompatibleDelegatingPasswordEncoderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilterTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/DynamicZoneAwareAuthenticationManagerTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsTests.java
Labels: scheduled

#1699 add random device for cargo start
  build.gradle
Labels: unscheduled

#1700 increase randomness of authcode
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStoreTests.java
Labels: unscheduled, scheduled
