Repository cloudfoundry/uaa, pull requests merged in 2021-03, with the labels that each got.

#1429 Fix typo
  uaa/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/DynamicZoneAwareAuthenticationManagerTest.java
Labels: unscheduled, waiting-cla

#1512 refactor: implement recommendation from thymeleaf
  server/src/main/java/org/cloudfoundry/identity/uaa/login/ThymeleafConfig.java
  server/src/main/resources/templates/web/access_confirmation.html
  server/src/main/resources/templates/web/access_confirmation_error.html
  server/src/main/resources/templates/web/accounts/email_sent.html
  server/src/main/resources/templates/web/accounts/link_prompt.html
  server/src/main/resources/templates/web/accounts/new_activation_email.html
  server/src/main/resources/templates/web/approvals.html
  server/src/main/resources/templates/web/change_email.html
  server/src/main/resources/templates/web/change_password.html
  server/src/main/resources/templates/web/email_sent.html
  server/src/main/resources/templates/web/error.html
  server/src/main/resources/templates/web/external_auth_error.html
  server/src/main/resources/templates/web/force_password_change.html
  server/src/main/resources/templates/web/forgot_password.html
  server/src/main/resources/templates/web/home.html
  server/src/main/resources/templates/web/idp_discovery/account_chooser.html
  server/src/main/resources/templates/web/idp_discovery/email.html
  server/src/main/resources/templates/web/idp_discovery/password.html
  server/src/main/resources/templates/web/invalid_request.html
  server/src/main/resources/templates/web/invitations/accept_invite.html
  server/src/main/resources/templates/web/login.html
  server/src/main/resources/templates/web/login_implicit.html
  server/src/main/resources/templates/web/mfa/enter_code.html
  server/src/main/resources/templates/web/mfa/manual_registration.html
  server/src/main/resources/templates/web/mfa/qr_code.html
  server/src/main/resources/templates/web/passcode.html
  server/src/main/resources/templates/web/reset_password.html
  server/src/main/resources/templates/web/switch_idp.html
Labels: unscheduled

#1538 Dependency Updates
  dependencies.gradle
Labels: dependencies, java, unscheduled
