Repository cloudfoundry/uaa, pull requests merged in 2021-07, with the labels that each got.

#1322 Refactor: query minimal user information everywhere authorities not needed
  server/src/main/java/org/cloudfoundry/identity/uaa/account/UserInfoEndpoint.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/SessionResetFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaPrincipal.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUser.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUserDatabase.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/InMemoryUaaUserDatabase.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/InMemoryUaaUserDatabaseTests.java
Labels: performance

#1562 Performance optimation: Prevent expensive duplicate key exception and use upsert instead
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/JdbcRevocableTokenProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/RevocableTokenProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenTestSupport.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/JdbcRevocableTokenProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/IdentityZoneModifiedEventTest.java
Labels: performance

#1596 Bump dependency
  uaa/slate/package.json
Labels: unscheduled

#1594 Set startStopTimeout to be configurable
  build.gradle
Labels: unscheduled

#1563 Return existing records on update failure
  dependencies.gradle
  server/build.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCache.java
  server/src/main/java/org/cloudfoundry/identity/uaa/cache/StaleUrlCache.java
  server/src/test/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCacheTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/cache/StaleUrlCacheTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerGithubTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfiguratorTest.java
Labels: in progress

#1600 Bump maven dependencies
  server/pom.xml
  statsd/pom.xml
  uaa/pom.xml
Labels: unscheduled

#939 PKCE support according to RFC 7636
  model/src/main/java/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.java
  model/src/test/java/org/cloudfoundry/identity/uaa/account/OpenIdConfigurationTests.java
  model/src/test/resources/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration-nulls.json
  model/src/test/resources/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.json
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationEndpoint.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceValidationException.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceValidationService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceVerifier.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/verifiers/PlainPkceVerifier.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/verifiers/S256PkceVerifier.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranter.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationEndpointParamaterizedTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceValidationServiceTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/pkce/verifiers/PlainPkceVerifierTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/pkce/verifiers/S256PkceVerifierTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/UaaTestAccounts.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/AuthorizationCodeGrantIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AuthorizeEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/OpenIdConnectEndpointDocs.java
Labels: accepted

#1604 Add property option for mail.smtp.ssl.protocols
  server/src/main/resources/spring/login-ui.xml
Labels: unscheduled

#1605 Add property option for mail.smtp.ssl.protocols
  k8s/matchers/uaa_config_structs.go
  k8s/templates/uaa.lib.yml
  k8s/templates/values/_values.yml
  k8s/test/config_map_test.go
  server/src/main/resources/spring/login-ui.xml
Labels: unscheduled

#1601 Bump spring oauth2 version to 2.5.1.RELEASE
  dependencies.gradle
Labels: dependencies, unscheduled

#1254 Add workaround for revoke access dialog from issue #1036
  uaa/src/main/webapp/resources/oss/stylesheets/application.css
Labels: unscheduled

#1611 Bump Spring Dependencies
  dependencies.gradle
Labels: dependencies, java, unscheduled

#1612 Bump passay version 1.6.1
  dependencies.gradle
Labels: dependencies

#1613 Feature/redirect uri path traversal
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/beans/LegacyRedirectResolverTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Labels: unscheduled

#1616 Bump commons-io from 2.10.0 to 2.11.0
  dependencies.gradle
  model/pom.xml
Labels: dependencies, unscheduled
