Repository cloudfoundry/uaa, pull requests merged in 2021-09, with the labels that each got.

#1661 bump dependency to jakarta.el 3.0.4
  uaa/build.gradle
Labels: dependencies

#1652 Add Vendor specific statements to retrieve authorities for user
  server/src/main/java/org/cloudfoundry/identity/uaa/db/Vendor.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/approval/ApprovalsAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabaseTests.java
Labels: unscheduled

#1651 Fixes #1636 Client creation endpoint does not accept two secrets to s…
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/client/ClientDetailsCreation.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientAdminEndpointsIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointsMockMvcTests.java
Labels: unscheduled

#1665 Fix for provider origin / type check
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderConfigValidationDelegator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderConfigValidationDelegatorTest.java
Labels: bug

#1667 Bump Spring Dependencies
  dependencies.gradle
Labels: dependencies

#1664 Fix issue #1628
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsTests.java
Labels: bug

#1668 support logout for OpenId proxy mode
  model/src/main/java/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.java
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractExternalOAuthIdentityProviderDefinition.java
  model/src/test/java/org/cloudfoundry/identity/uaa/account/OpenIdConfigurationTests.java
  model/src/test/resources/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration-nulls.json
  model/src/test/resources/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.json
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/WhitelistLogoutHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ZoneAwareWhitelistLogoutHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExernalOAuthLogoutHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadata.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadataFetcher.java
  server/src/main/resources/spring/login-ui.xml
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/ZoneAwareWhitelistLogoutHandlerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExernalOAuthLogoutHandlerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
Labels: feature proposal
