Repository cloudfoundry/uaa, pull requests merged in 2022-10, with the labels that each got.

#2049 fix sonar smells
  server/src/main/java/org/cloudfoundry/identity/uaa/security/LdapSocketFactory.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/SkipSslLdapSocketFactory.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/CorsFilterDefaultZoneTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/CorsFilterNonDefaultZoneTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/CookieBasedCsrfTokenRepositoryTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/SessionControllerIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Labels: unscheduled

#2051 Add test for copy-to-clipboard functionality in `passcode` page
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
Labels: unscheduled

#2054 Update UAA server debug mode run options
  README.md
  build.gradle
Labels: unscheduled

#2063 feature: Set LDAP connection timeout to 30 minutes
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/LdapIntegrationConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/BaseLdapSocketFactory.java
  server/src/test/java/org/cloudfoundry/identity/uaa/impl/config/LdapIntegrationConfigTest.java
Labels: unscheduled

#2069 Refactor refreshAccessToken()
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
Labels: unscheduled

#2070 Revert codestore random generator
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/CodeStoreEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStoreTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/InMemoryExpiringCodeStore.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/PasscodeMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/PasswordResetEndpointMockMvcTests.java
Labels: unscheduled

#2068 Document how to run local UAA server with different databases
  README.md
Labels: unscheduled

#2072 increase randomness of passcode
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/CodeStoreEndpointsTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/AutologinIT.java
Labels: unscheduled

#2071 Refactor UaaTokenServices
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/BackwardsCompatibleTokenEndpointAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/RefreshRotationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenTestSupport.java
Labels: unscheduled

#2075 Bump nimbus-jose-jwt from 8.23 to 9.24.4
  dependencies.gradle
Labels: unscheduled

#2076 Use jackson in jsonpath and exclude json-smart library
  server/build.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/JacksonObjectMapperConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java
Labels: unscheduled

#2077 build(deps): bump passay from 1.6.1 to 1.6.2
  dependencies.gradle
Labels: dependencies, java

#2078 Simplify ignore in dependabot
  .github/dependabot.yml
Labels: dependencies, in_review
