Repository cloudfoundry/uaa, pull requests merged in 2022-11, with the labels that each got.

#2087 dependency update (#1478)
  dependencies.gradle
  server/build.gradle
  server/src/test/resources/messages.properties
Labels: unscheduled

#2091 doc: Add a section decsribing how to run local UAA server with PostgreSQL
  README.md
Labels: unscheduled

#2099 Upgrade Tomcat cargo version 9.0.69
  dependencies.gradle
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/FormLoginIntegrationTests.java
Labels: unscheduled, dependencies, java

#2104 Bump snakeyaml 1.33
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2103 Bump mariadb version 2.7.7
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2101 Fix error "rawPassword cannot be null" and prevent null in password encoder
  server/src/main/java/org/cloudfoundry/identity/uaa/util/beans/BackwardsCompatibleDelegatingPasswordEncoder.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapMultipleSecretsUpdateTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapTests.java
Labels: bug

#2093 Updating Readme & Adding LDAP Setup Option
  README.md
  scripts/ldap/docker-compose.yml
  scripts/ldap/docker-confirm-ldapquery.sh
  uaa/src/main/resources/uaa.yml
Labels: unscheduled

#2107 Docs for setting up ldap local
  README.md
  scripts/ldap/docker-compose.yml
  scripts/ldap/docker-confirm-ldapquery.sh
  scripts/ldap/mac-ldap-install.sh
  scripts/ldap/mac-ldap-run.sh
  scripts/ldap/slapd.conf
  uaa/src/main/resources/uaa.yml
Labels: unscheduled

#2108 Docs for setting up ldap local (#2107)
  README.md
  scripts/ldap/docker-compose.yml
  scripts/ldap/docker-confirm-ldapquery.sh
  scripts/ldap/mac-ldap-install.sh
  scripts/ldap/mac-ldap-run.sh
  scripts/ldap/slapd.conf
  uaa/src/main/resources/uaa.yml
Labels: unscheduled

#2105 RateLimit Change: Use nanoTime time instead of currentTimeMillis
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/config/InitialConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/config/RateLimitingConfigMapperImpl.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/RateLimiterStatus.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/ExpirationBuckets.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/LimiterByCompoundKey.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/LimiterManagerImpl.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/util/MillisTimeSupplier.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/util/NanoTimeSupplier.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/config/InitialConfigTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/config/RateLimitingConfigMapperImplTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/ExpirationBucketsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/InternalLimiterFactoryImplTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/LimiterByCompoundKeyTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/internal/limitertracking/LimiterManagerImplTest.java
Labels: unscheduled

#2117 Create sonarcloudpr.yml
  .github/workflows/sonarcloudpr.yml
Labels: unscheduled

#2120 Revert "Create sonarcloudpr.yml"
  .github/workflows/sonarcloudpr.yml
Labels: unscheduled
