Repository cloudfoundry/uaa, pull requests merged in 2022-02, with the labels that each got.

#1786 bump xerces:xercesImpl 2.12.2
  dependencies.gradle
  server/build.gradle
Labels: unscheduled, dependencies, java

#1791 k8s update
  k8s/templates/values/image.yml
  k8s/templates/values/version.yml
Labels: unscheduled

#1792 revert
  k8s/templates/values/version.yml
Labels: unscheduled

#1794 Fix SAML Idp login check
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/PasswordChangeUiRequiredFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/mfa/MfaUiRequiredFilter.java
  server/src/main/resources/spring/login-ui.xml
Labels: unscheduled, scheduled
