Repository cloudfoundry/uaa, pull requests merged in 2022-07, with the labels that each got.

#1931 doc: update sample curl output
  README.md
Labels: unscheduled

#1942 fix: Test for JWT Bearer Endpoint Docs
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/JwtBearerGrantEndpointDocs.java
Labels: unscheduled

#1934 Update infos for community
  README.md
Labels: unscheduled, documentation

#1947 feat: Port over changes in release v74.5.26 into OSS UAA
  server/src/test/java/org/cloudfoundry/identity/uaa/db/SpringSessionAttributesTableTest.java
Labels: unscheduled

#1955 Upgrade Tomcat cargo version 9.0.65
  dependencies.gradle
Labels: unscheduled

#1957 Fix SAML login flow by configuring JSESSIONID cookie
  server/src/main/java/org/cloudfoundry/identity/uaa/web/beans/UaaSessionConfig.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/FormLoginIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
Labels: unscheduled

#1965 CVE-2022-34169: omit xalan
  server/build.gradle
Labels: unscheduled, dependencies, java

#1950 Porting lts uaa version v74.5.32 that upgrades flyway to version 7 and adding mysql 8 support
  README.md
  build.gradle
  dependencies.gradle
  run-integration-tests.sh
  run-unit-tests.sh
  server/src/main/java/org/cloudfoundry/identity/uaa/db/BootstrapIdentityZones.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/Create_Groups_For_Zones_2_5_2.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/DatabaseInformation1_5_3.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/FixFailedBackportMigrations_4_0_4.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/InitialPreDatabaseVersioningSchemaCreator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/MigrateGroupZones_2_4_2.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/V2_7_3__StoreSubDomainAsLowerCase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/hsqldb/V2_5_3__Migrate_Groups_For_Zones.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/hsqldb/V2_7_3__StoreSubDomainAsLowerCase__Migrate_Zone_Subdomain_To_Lowercase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V1_5_4__NormalizeTableAndColumnNames.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V2_5_3__Migrate_Groups_For_Zones.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V2_7_3__StoreSubDomainAsLowerCase__Migrate_Zone_Subdomain_To_Lowercase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V4_9_2__AddPrimaryKeysIfMissing.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/postgresql/V1_5_3__InitialDBScript.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/postgresql/V1_5_4__NormalizeTableAndColumnNames.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/postgresql/V2_5_3__Migrate_Groups_For_Zones.java
  server/src/main/java/org/cloudfoundry/identity/uaa/db/postgresql/V2_7_3__StoreSubDomainAsLowerCase__Migrate_Zone_Subdomain_To_Lowercase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/error/UaaDBException.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupExternalMembershipManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/beans/DbUtils.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V1_5_2__initial_db.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V2_4_1__Zonify_Group_Memberships.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V2_5_1__Fix_Null_Values_In_GroupMbr_ZoneId.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V2_5_2__Zonify_Groups.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V3_0_1__Add_Group_Description.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_0_6__Add_Identity_Zone_Id_To_Tables.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/CheckIdpEnabledAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authorization/external/LdapGroupMappingAuthorizationManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/DbMigrationIntegrationTestParent.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/MigrationTestRunner.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/MySqlDbMigrationIntegrationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/V2_7_3__StoreSubDomainAsLowerCase_Tests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/extensions/PollutionPreventionExtension.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/JdbcQueryableClientDetailsServiceTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/approval/ApprovalsAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimExternalGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupExternalMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioningTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/TestUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabaseTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/beans/DbUtilsTest.java
Labels: dependencies, java, in_review

#1967 make DB test script compatible with postgres 13 docker image
  scripts/start_db_helper.sh
Labels: unscheduled

#1968 Fix postgres migration test failure
  server/src/test/java/org/cloudfoundry/identity/uaa/db/MigrationTestRunner.java
Labels: unscheduled

#1966 Feat/port 74.5.35
  samples/api/src/main/webapp/WEB-INF/web.xml
  scripts/start_db_helper.sh
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/GeneralIdentityZoneConfigurationValidator.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_0_9__ExtendClientAuthScopeSize.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/GeneralIdentityZoneConfigurationValidatorTests.java
Labels: unscheduled

#1970 fix password integration test
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/PasswordIT.java
Labels: unscheduled

#1971 fix sonar findings
  server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/SpringSessionAttributesTableTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/db/V2_7_3__StoreSubDomainAsLowerCase_Tests.java
Labels: unscheduled

#1972 Bump Gradle to 7.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#1973 feat: slack info
  README.md
Labels: unscheduled

#1975 fix increase webdriver timeouts for integration tests
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/DefaultIntegrationTestConfig.java
Labels: unscheduled
