Repository cloudfoundry/uaa, pull requests merged in 2022-08, with the labels that each got.

#1977 feature: Move inline javascript to an external .js file
  server/src/main/resources/templates/web/approvals.html
  uaa/src/main/webapp/resources/javascripts/approvals/click_actions.js
Labels: unscheduled

#1978 feat/port-74.5.41
  build.gradle
  dependencies.gradle
Labels: unscheduled

#1974 Feat/port 74.5.36
  metrics-data/pom.xml
  model/pom.xml
  run-integration-tests.sh
  samples/api/pom.xml
  samples/app/pom.xml
  samples/pom.xml
  scripts/integration-tests.sh
  server/pom.xml
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/CurrentUserCookieRequestFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/metrics/UaaMetricsFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/CookieBasedCsrfTokenRepository.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/CorsFilter.java
  server/src/main/resources/templates/web/idp_discovery/account_chooser.html
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/CurrentUserCookieRequestFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandlerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/CsrfAwareEntryPointAndDeniedHandlerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/CorsFilterDefaultZoneTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/CorsFilterNonDefaultZoneTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/CookieBasedCsrfTokenRepositoryTests.java
  statsd/pom.xml
  uaa/pom.xml
  uaa/src/main/resources/uaa.yml
  uaa/src/main/webapp/WEB-INF/spring-servlet.xml
  uaa/src/main/webapp/resources/javascripts/account_chooser/saved_account_click_action.js
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/TotpMfaEndpointIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LdapLoginIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginWithLocalIdpIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Labels: unscheduled

#1982 Revert "Remove unnecessary version pinnings after bumping `spring-boot` to 2.6.8"
  dependencies.gradle
Labels: unscheduled

#1986 Feat port 74.5.33
  model/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaProviderTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/SimpleSearchQueryConverter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/AlphanumericRandomValueStringGenerator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/CodeStoreEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStoreTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/codestore/InMemoryExpiringCodeStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/GeneralMfaProviderValidatorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/ScimSearchQueryConverterTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsEndpointMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/ldap/AbstractLdapMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/mfa_provider/MfaProviderEndpointsMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/PasswordResetEndpointMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsMockMvcTests.java
Labels: unscheduled

#1990 Bump mariadb version 2.7.6
  dependencies.gradle
Labels: unscheduled, dependencies, java

#1992 Bump Gradle to 7.5.1
  gradle/wrapper/gradle-wrapper.properties
Labels: unscheduled, dependencies, java

#1993 fix https://github.com/cloudfoundry/uaa/issues/1983
  server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java
  server/src/main/resources/spring/env.xml
  server/src/test/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabaseTests.java
Labels: unscheduled, performance, java

#2011 docs: Add deprecation notice for Google Analytics
  README.md
Labels: unscheduled

#1981 Port over 74.5.39 features
  server/src/main/java/org/cloudfoundry/identity/uaa/login/TotpMfaEndpoint.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilter.java
  server/src/main/resources/templates/web/layouts/main.html
  server/src/main/resources/templates/web/mfa/enter_code.html
  server/src/main/resources/templates/web/session.html
  server/src/main/resources/templates/web/session_management.html
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
  uaa/src/main/webapp/resources/javascripts/last_login_time.js
  uaa/src/main/webapp/resources/javascripts/session/session_management_message_handler.js
  uaa/src/main/webapp/resources/javascripts/session/session_message_handler.js
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/SessionControllerIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
Labels: unscheduled
