Repository cloudfoundry/uaa, pull requests merged in 2022-06, with the labels that each got.

#1899 Remove more String Passwords variables reported in the Issue#1838
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/LdapIdentityProviderDefinition.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/NonStringPassword.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/PasscodeAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/KeystoneAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/RestAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderValidationRequest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/ldap/PasswordComparisonAuthenticator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/ldap/extension/ExtendedLdapUserImpl.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/SamlKeyManagerFactory.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/ScimUserProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUser.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUserEditor.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUserPrototype.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/PasscodeAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderValidationRequestTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/ldap/ExtendedLdapUserMapperTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/ldap/LdapIdentityProviderDefinitionTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/UaaTestAccounts.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/UaaUserEditorTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/user/UaaUserPrototypeTest.java
Labels: unscheduled

#1888 [PKCE] allowpublic client option for grant_type authorization_code using PKCE with S256 method
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/client/ClientConstants.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ClientDetailsAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrap.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/UaaClient.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/UaaClientDetailsUserDetailsService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/UaaConfiguration.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceValidationService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranter.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapMultipleSecretsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/pkce/PkceValidationServiceTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranterTest.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
Labels: unscheduled, feature proposal

#1921 fix some sonar smells
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderValidationRequest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/ldap/extension/ExtendedLdapUserImpl.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/ldap/LdapIdentityProviderDefinitionTest.java
Labels: unscheduled

#1922 fix http 500 for SAML generic calls
  server/src/main/java/org/cloudfoundry/identity/uaa/home/HomeController.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlDiscovery.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/HomeControllerViewTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlDiscoveryTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java
Labels: unscheduled

#1924 prevent null pointer
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpoint.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java
Labels: unscheduled, bug

#1928 file paths to be quoted in gradle script
  build.gradle
Labels: unscheduled

#1925 fix id_token mapping
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java
Labels: unscheduled

#1926 Use login.url for password reset email template creation
  server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordController.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerMockMvcTests.java
Labels: unscheduled

#1929 refactor check of MFA name
  server/src/main/java/org/cloudfoundry/identity/uaa/mfa/GeneralMfaProviderValidator.java
Labels: unscheduled
