Repository cloudfoundry/uaa, pull requests merged in 2022-09, with the labels that each got.

#2022 feat: Removed google analytics feature
  README.md
  server/src/main/resources/templates/web/layouts/main.html
  uaa/src/main/resources/uaa.yml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Labels: unscheduled

#2024 docs: Added MFA deprecated notice and updated support text
  README.md
  server/src/main/resources/templates/web/mfa/enter_code.html
Labels: unscheduled

#2023 Bump snakeyaml version from 1.30 to 1.32
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2033 Update jQuery version to v3.6.1
  uaa/src/main/webapp/vendor/jquery/javascripts/jquery.js
Labels: dependencies, javascript

#2034 fix issue with broken copy button
  server/src/main/resources/templates/web/passcode.html
  uaa/src/main/webapp/resources/javascripts/passcode/copy_clipboard.js
Labels: unscheduled

#2041 Bump spring boot patch to 2.6.12
  dependencies.gradle
Labels: unscheduled

#2035 Fix regression with legacy redirect patterns
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/beans/LegacyRedirectResolver.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/beans/LegacyRedirectResolverTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Labels: unscheduled
