Repository cloudfoundry/uaa, pull requests merged in 2022-04, with the labels that each got.

#1846 do always a retry in unit tests
  build.gradle
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/JdbcAuditServiceTests.java
Labels: unscheduled

#1845 Bump versions.bouncyCastleVersion from 1.70 to 1.71
  dependencies.gradle
  server/build.gradle
Labels: dependencies, java

#1850 remove gradle deprecated plugins
  build.gradle
Labels: unscheduled, dependencies

#1847 SonarQube for UAA CI
  build.gradle
  dependencies.gradle
Labels: unscheduled, java

#1851 sonar
  .github/workflows/sonarcloud.yml
Labels: unscheduled

#1848 sonar refactorings
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpoints.java
Labels: unscheduled

#1849 sonar fixes
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/SamlIdentityProviderDefinition.java
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderDefinition.java
  model/src/main/java/org/cloudfoundry/identity/uaa/util/ObjectUtils.java
  model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java
  model/src/test/java/org/cloudfoundry/identity/uaa/util/ObjectUtilsTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/approval/ApprovalsAdminEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/approval/JdbcApprovalStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/AbstractClientParametersAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/AuthzAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/BackwardsCompatibleTokenEndpointAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/LoginClientParametersAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/JdbcClientMetadataProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/DisableIdTokenResponseTypeFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/OpenIdSessionStateCalculator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpInitiatedLoginController.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneEndpoints.java
Labels: unscheduled

#1854 cleanup sonarcloud action
  .github/workflows/sonarcloud.yml
Labels: unscheduled

#1853 chore: Set permissions for GitHub actions
  .github/workflows/gradle.yml
Labels: unscheduled

#1856 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: unscheduled

#1857 exclude tests from sonar scan
  build.gradle
Labels: unscheduled

#1855 bump dependency of owasp esapi version 2.4.0.0
  dependencies.gradle
  server/build.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/saml/SamlAuthenticationMockMvcTests.java
Labels: dependencies, java

#1860 Update UAA image reference in k8s deployment template to 75.19.0
  k8s/templates/values/image.yml
Labels: unscheduled

#1859 chore(deps): Included dependency review
  .github/workflows/depsreview.yml
Labels: unscheduled

#1863 fix sonar issues
  metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util/JsonUtils.java
  model/src/main/java/org/cloudfoundry/identity/uaa/scim/impl/ScimUserJsonDeserializer.java
  server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/account/UaaResetPasswordService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/beans/LegacyRedirectResolver.java
Labels: unscheduled

#1866 test class
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/AutologinRequestConverterTest.java
Labels: unscheduled

#1867 sonar recommendations about long cast
  server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/TimeBasedExpiringValueMap.java
Labels: unscheduled
