Repository cloudfoundry/uaa, pull requests merged in 2023-07, with the labels that each got.

#2396 Bump Gradle to 8.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: unscheduled

#2399 Extend test coverage in OauthIDPWrapperFactoryBean
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
Labels: unscheduled, java

#2385 feature: Store client authentication method in JWT
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/ClaimConstants.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/AbstractClientParametersAuthenticationFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ClientDetailsAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaAuthenticationDetails.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/openid/UserAuthenticationData.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaSecurityContextUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/ClientParametersAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/openid/IdTokenCreatorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaSecurityContextUtilsTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled

#2347 fix: make kill more reliable
  scripts/kill_uaa.sh
Labels: unscheduled

#2404 Add Introspection Claims Test
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/Claims.java
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/TokenConstants.java
  model/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/IntrospectionClaimsTest.java
Labels: unscheduled

#2403 internal tests only: define more values in uaa.yml
  scripts/cargo/uaa.yml
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
Labels: unscheduled

#2315 Refactor: Add Instant to TimeService interface and use TimeService in UaaTokenStore
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/TimeService.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStoreTests.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
Labels: unscheduled

#2397 feature: Allow sending static key/value pairs to the configured IdP
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/OIDCIdentityProviderDefinition.java
  model/src/test/java/org/cloudfoundry/identity/uaa/provider/OIDCIdentityProviderDefinitionTests.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthIdentityProviderConfigValidator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfigurator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthIdentityProviderConfigValidatorTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfiguratorTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: scheduled

#2402 feature: allow refresh flow for public usages
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ClientDetailsAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaAuthenticationDetails.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/ClientParametersAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaAuthenticationDetailsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaAuthenticationSerializationTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaAuthenticationTestFactory.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/AuthzAuthenticationManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/RefreshRotationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/PkceEnhancedAuthorizationCodeTokenGranterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationFilterTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaSecurityContextUtilsTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled, java

#2405 uaa-ci: use RS256 key as default
  scripts/cargo/uaa.yml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/logout/LogoutInfoEndpointDocs.java
  uaa/src/test/resources/integration_test_properties.yml
Labels: expected behavior

#2414 Fix UAA startup if postgresql is used for session store
  scripts/cargo/uaa.yml
  server/src/main/java/org/cloudfoundry/identity/uaa/web/beans/UaaSessionConfig.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/beans/UaaSessionConfigTest.java
Labels: unscheduled

#2420 feature: Use custom key in private_key_jwt towards OAuth2/OIDC IdP
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthentication.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthenticationTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled, in_review

#2422 Delete unused script & dockerfile
  ci/image/Dockerfile
  ci/image/copy_of-uaa_src_main_resources_ldap_init.ldif
  ci/image/ldap_db_init.ldif
  scripts/docker_run
Labels: unscheduled

#2406 Change default of refresh token format
  model/src/main/java/org/cloudfoundry/identity/uaa/zone/TokenPolicy.java
  model/src/test/java/org/cloudfoundry/identity/uaa/zone/TokenPolicyTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/DeprecatedUaaTokenServicesTests.java
  uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/RefreshTokenMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
  uaa/src/test/resources/integration_test_properties.yml
Labels: unscheduled, expected behavior, in_review

#2424 Bump Gradle to 8.2.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, java

#2423 fix: expired X509 certificates should be ignored for JWT usage
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/KeyInfo.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtHelper.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthenticationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtHelperX5tTest.java
  server/src/test/resources/org/cloudfoundry/identity/uaa/oauth/jwt/expired_certificate.pem
Labels: unscheduled, bug
