Repository cloudfoundry/uaa, pull requests merged in 2023-06, with the labels that each got.

#2356 Revert "build(deps): bump org.seleniumhq.selenium:selenium-http-jdk-client from 4.9.1 to 4.10.0"
  dependencies.gradle
Labels: in progress

#2361 Upgrade Tomcat cargo version 9.0.76
  dependencies.gradle
Labels: unscheduled

#2363 Remove deprecated code for performance logs
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/DefaultIntegrationTestConfig.java
Labels: unscheduled

#2343 Support json key set in tokenKey
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeySet.java
  model/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeyTests.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeyHelper.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeySetTests.java
Labels: unscheduled

#2377 Bump jackson version 2.14.3 to 2.15.2
  dependencies.gradle
Labels: unscheduled, in progress

#2372 Delete all user group members if user is deleted
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpoints.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsTests.java
Labels: unscheduled

#2386 Build fix
  build.gradle
  uaa/build.gradle
Labels: unscheduled

#2387 fix typo
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/CommonSigner.java
Labels: unscheduled
