Repository cloudfoundry/uaa, pull requests merged in 2023-02, with the labels that each got.

#2150 Documentation recommendations according usage of relyingPartySecret
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled, documentation

#2168 Configure Content Security Policy script-src
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilter.java
  server/src/test/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilterTest.java
  uaa/src/main/webapp/WEB-INF/spring-servlet.xml
Labels: unscheduled, accepted, feature proposal, java

#2195 Refactor: YAML processor from spring
  run-unit-tests.sh
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlMapFactoryBean.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlProcessor.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlPropertiesFactoryBean.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java
  server/src/main/java/org/cloudfoundry/identity/uaa/metrics/UaaMetricsFilter.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/config/InitialConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/config/YamlConfigFileDTO.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaYamlUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/YamlBindingTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/YamlConfigurationValidatorTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/YamlMapFactoryBeanTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/YamlPropertiesFactoryBeanTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/mfa/MfaProviderBootstrapTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/ldap/LdapIdentityProviderDefinitionTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/BootstrapSamlIdentityProviderDataTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/config/RateLimitingConfigMapperImplTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/TestProfileEnvironment.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/NestedMapPropertySourceFactory.java
Labels: unscheduled

#2181 Refactor: Use Constants
  model/build.gradle
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKey.java
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeyDeserializer.java
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeySerializer.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/KeyInfo.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java
Labels: unscheduled

#2210 Fix pemEncodePublicKey
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKey.java
Labels: unscheduled

#2215 Update UAA image reference in k8s deployment template to 76.6.0
  k8s/templates/values/image.yml
  k8s/templates/values/version.yml
Labels: unscheduled
