Repository cloudfoundry/uaa, pull requests merged in 2023-10, with the labels that each got.

#2516 test clean-up: switch back to using standard simplesamlPHP server URL
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
Labels: unscheduled

#2518 Bump dependency org.gradle:test-retry-gradle-plugin to v1.5.6
  dependencies.gradle
Labels: dependencies, java

#2519 delete unused pom.xml
  statsd-lib/pom.xml
Labels: unscheduled

#2513 build: change sonar runner to java 17
  .github/workflows/sonarcloud.yml
  dependencies.gradle
Labels: unscheduled, dependencies, java, github_actions

#2521 fix: json syntax error
  uaa/slate/package.json
Labels: unscheduled

#2524 Bump Gradle to 8.4
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: unscheduled, java

#2525 Bump dependencies in package.json of slate (doc)
  uaa/slate/package.json
Labels: unscheduled, dependencies, javascript

#2531 fix sonar finding: duplicate string literals
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
Labels: unscheduled

#2533 fix sonar issue: Utility classes should not have public constructors
  metrics-data/src/main/java/org/cloudfoundry/identity/uaa/metrics/MetricsUtil.java
Labels: unscheduled

#2541 Bump jackson version 2.15.2 to 2.15.3
  dependencies.gradle
Labels: dependencies, java

#2509 feature: publish in well-known and document private_key_jwt parameters in rest API
  model/src/main/java/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.java
  model/src/test/java/org/cloudfoundry/identity/uaa/account/OpenIdConfigurationTests.java
  model/src/test/resources/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.json
  uaa/slateCustomizations/source/index.html.md.erb
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/JwtBearerGrantEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/JwtBearerGrantMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/OpenIdConnectEndpointsMockMvcTests.java
Labels: unscheduled

#2508 test: Add Client Authentication Integration Tests
  server/src/test/resources/integration.test.properties
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/PrivateKeyJwtClientAuthIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/TestClient.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
Labels: unscheduled, in_review

#2551 doc: announcement for private_key_jwt
  docs/UAA-Client-Authentication.md
Labels: unscheduled, documentation

#2526 sonar fix
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/config/InitialConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/ratelimiting/util/SourcedFile.java
  server/src/test/java/org/cloudfoundry/identity/uaa/ratelimiting/util/SourcedFileTest.java
  server/src/test/resources/uaa-ratelimit.yml
Labels: unscheduled

#2563 fix: java version requirement in README
  README.md
Labels: unscheduled

#2520 documentation: update system admin guide
  docs/Sysadmin-Guide.rst
Labels: unscheduled, documentation

#2549 fix: unnecessary method call
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java
Labels: unscheduled

#2564 bump: Bouncy Castle dependencies
  LICENSE
  dependencies.gradle
  server/build.gradle
  uaa/build.gradle
Labels: unscheduled, LTS-PR

#2565 fix flaky test
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled

#2504 feature: add client_auth_method=none into tokens for clients with empty secret
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/TokenConstants.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ClientDetailsAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/RefreshRotationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/UaaTestAccounts.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/PasswordGrantIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/RefreshTokenSupportIntegrationTests.java
Labels: unscheduled

#2573 fix: cve-scanner failure
  build.gradle
  uaa/build.gradle
  uaa/slate/.gitignore
  uaa/slate/CHANGELOG.md
  uaa/slate/Gemfile
  uaa/slate/Gemfile.lock
  uaa/slate/LICENSE
  uaa/slate/README.md
  uaa/slate/Vagrantfile
  uaa/slate/config.rb
  uaa/slate/deploy.sh
  uaa/slate/font-selection.json
  uaa/slate/gulpfile.js
  uaa/slate/lib/monokai_sublime_slate.rb
  uaa/slate/lib/multilang.rb
  uaa/slate/lib/toc_data.rb
  uaa/slate/lib/unique_head.rb
  uaa/slate/package-lock.json
  uaa/slate/package.json
  uaa/slate/source/fonts/slate.eot
  uaa/slate/source/fonts/slate.svg
  uaa/slate/source/fonts/slate.ttf
  uaa/slate/source/fonts/slate.woff
  uaa/slate/source/fonts/slate.woff2
  uaa/slate/source/images/navbar.png
  uaa/slate/source/includes/_errors.md
  uaa/slate/source/index.html.md
  uaa/slate/source/javascripts/all.js
  uaa/slate/source/javascripts/all_nosearch.js
  uaa/slate/source/javascripts/app/_lang.js
  uaa/slate/source/javascripts/app/_search.js
  uaa/slate/source/javascripts/app/_toc.js
  uaa/slate/source/javascripts/app/_version_dropdown.js
  uaa/slate/source/javascripts/lib/_dropdown.js
  uaa/slate/source/javascripts/lib/_energize.js
  uaa/slate/source/javascripts/lib/_imagesloaded.min.js
  uaa/slate/source/javascripts/lib/_jquery.highlight.js
  uaa/slate/source/javascripts/lib/_jquery.js
  uaa/slate/source/javascripts/lib/_lunr.js
  uaa/slate/source/layouts/layout.erb
  uaa/slate/source/stylesheets/_dropdown.scss
  uaa/slate/source/stylesheets/_icon-font.scss
  uaa/slate/source/stylesheets/_normalize.scss
  uaa/slate/source/stylesheets/_variables.scss
  uaa/slate/source/stylesheets/print.css.scss
  uaa/slate/source/stylesheets/screen.css.scss
  uaa/slateCustomizations/source/images/logo.png
  uaa/slateCustomizations/source/index.html.md.erb
Labels: unscheduled

#2574 validate secrets only with text
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidatorTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientAdminEndpointsIntegrationTests.java
Labels: unscheduled
