Repository cloudfoundry/uaa, pull requests merged in 2023-11, with the labels that each got.

#2580 update dependency middleman to v4.5.1
  uaa/slate/Gemfile.lock
Labels: unscheduled, dependencies, ruby, DO NOT MERGE

#2585 Update OIDC integration documentation
  docs/OIDC-Provider-Examples/google-oidc-provider.md
  docs/OIDC-Provider-Examples/microsoft-oidc-provider.md
  docs/OIDC-Provider-Examples/okta-public-oidc-provider.md
  docs/OIDC-Provider-Examples/sap-public-oidc-provider.md
Labels: unscheduled, documentation

#2592 fix sonar finding
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
Labels: unscheduled

#2594 Bump mariadb from 2.7.10 to 2.7.11
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2588 Add label text to all form controls
  server/src/main/resources/templates/web/accounts/new_activation_email.html
  server/src/main/resources/templates/web/change_email.html
  server/src/main/resources/templates/web/change_password.html
  server/src/main/resources/templates/web/force_password_change.html
  server/src/main/resources/templates/web/forgot_password.html
  server/src/main/resources/templates/web/idp_discovery/email.html
  server/src/main/resources/templates/web/idp_discovery/origin.html
  server/src/main/resources/templates/web/idp_discovery/password.html
  server/src/main/resources/templates/web/invitations/accept_invite.html
  server/src/main/resources/templates/web/login.html
  server/src/main/resources/templates/web/mfa/enter_code.html
  server/src/main/resources/templates/web/reset_password.html
  uaa/slate/source/layouts/layout.erb
Labels: unscheduled

#2597 bump: Dependencies that we override from spring-boot bom
  dependencies.gradle
Labels: unscheduled, LTS-PR

#2596 return invalid_client in oauth2 error code
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaExceptionTranslator.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientInfoEndpointIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
Labels: unscheduled, in_review

#2605 Bump jackson from 2.15.3 to 2.16.0
  dependencies.gradle
Labels: in progress, accepted

#2609 fix slack in readme
  README.md
Labels: accepted, documentation

#2607 Add SAML IdP deprecation notice
  README.md
Labels: accepted, documentation

#2610 fix: exclude unused vulnerable transitive deps
  server/build.gradle
Labels: unscheduled, LTS-PR

#2611 refactor: move jakarta mail dependency to spring boot mail
  dependencies.gradle
  server/build.gradle
  uaa/build.gradle
Labels: unscheduled

#2623 renovate: update dependency org.gradle:test-retry-gradle-plugin to v1.5.7
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2626 Bump Gradle to 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: unscheduled, dependencies, java
