Repository cloudfoundry/uaa, pull requests merged in 2023-05, with the labels that each got.

#2292 Minimal Fix auth code cleanup function
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStoreTests.java
Labels: unscheduled

#2312 Bump Gradle to 8.1.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: unscheduled

#2273 Fix for ldap.ssl.skipverification
  server/src/main/java/org/cloudfoundry/identity/uaa/security/SkipSslLdapSocketFactory.java
Labels: unscheduled

#2314 Fix flaky test
  .github/dependabot.yml
  dependencies.gradle
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/PasscodeMockMvcTests.java
Labels: unscheduled

#2318 fix: Incorrect elapsed time determination
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStoreTests.java
Labels: unscheduled

#2321 Upgrade Tomcat cargo version 9.0.75
  dependencies.gradle
Labels: unscheduled

#2326 fix: Correcting mysql 5 backup to mysql 8 restore to align collation …
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_103__mysql_specific_align_collation.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_103__mysql_specific_align_collation.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_103__mysql_specific_align_collation.sql
Labels: in progress, accepted

#2341 Pr/bruce/refactor while condition
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
Labels: unscheduled

#2336 Bump jackson 2.14.2 to 2.14.3
  dependencies.gradle
Labels: dependencies, java

#2340 Fix RSA public key parser
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeyHelper.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/CommonSignatureVerifier.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/CommonSignatureVerifierTest.java
Labels: unscheduled

#2329 fix: exclude unsupported response types in exception
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationEndpoint.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/UaaRequestMatcher.java
Labels: unscheduled

#2349 fix: resolve cve with latest snakeyaml 2.0
  dependencies.gradle
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/CustomPropertyConstructor.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaYamlUtils.java
Labels: in progress, in_review
