Repository cloudfoundry/uaa, pull requests merged in 2023-08, with the labels that each got.

#2432 fix: update k8s to go 1.20
  k8s/go.mod
Labels: unscheduled

#2434 fix: Dependabot can't authenticate to the private package registry ht…
  build.gradle
Labels: unscheduled

#2436 Bump hsqldb version 2.7.1 to 2.7.2
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2194 integrationTest: Add IT for user_token grant variants
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/UserTokenGrantIT.java
Labels: unscheduled, expected behavior

#2437 fix: Move refresh rotate check to refresh flow
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/RefreshRotationTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled

#2451 fix https://github.com/cloudfoundry/uaa/security/dependabot/57
  uaa/slate/Gemfile.lock
Labels: unscheduled, ruby

#2453 Fix: UAA login page breaks when the product logo image is over 100000 characters
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MergedZoneBrandingInformation.java
  server/src/main/resources/templates/web/layouts/main.html
  server/src/main/resources/templates/web/layouts/pui-account-discovery-main.html
  server/src/main/resources/templates/web/layouts/pui-mfa-main.html
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Labels: bug, in_review
