Repository cloudfoundry/uaa, pull requests merged in 2023-04, with the labels that each got.

#2265 fix: Use short-circuit or operator in UserIdConversionEndpoints.checkFilter
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpointsTests.java
Labels: unscheduled

#2270 Remove unused Variable in LoginInfoEndpoint.evaluateLoginHint
  server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
Labels: unscheduled

#2271 refactor UAA token store: use good time types
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStoreTests.java
Labels: unscheduled

#2268 Fix indexOf Checks in KeystoneAuthenticationManager
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/KeystoneAuthenticationManager.java
Labels: unscheduled

#2269 Remove unnecessary References to "apache.directory" Library
  model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java
  model/src/test/java/org/cloudfoundry/identity/uaa/util/UaaStringUtilsTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/ClientDetailsAuthenticationProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/cypto/EncryptionKeyService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/security/ScimUserUpdateDiff.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Labels: unscheduled

#2285 fix for code smells
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/ErrorRoutingIT.java
Labels: unscheduled

#2281 fix: incorrect elapsed time determination
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
Labels: in progress, bug, performance, in_review

#2290 Upgrade Tomcat cargo version 9.0.74
  dependencies.gradle
Labels: unscheduled

#2297 bump springBootVersion from 2.7.10 to 2.7.11
  dependencies.gradle
Labels: unscheduled

#2294 TDD: add test for userinfo compare
  server/src/test/java/org/cloudfoundry/identity/uaa/user/UserInfoTest.java
Labels: unscheduled

#2257 fix: Update gem setting to latest slate version
  LICENSE
  uaa/build.gradle
  uaa/slate/Gemfile
  uaa/slate/Gemfile.lock
  uaa/slate/config.rb
  uaa/slate/lib/monokai_sublime_slate.rb
  uaa/slate/source/layouts/layout.erb
  uaa/slate/source/stylesheets/screen.css.scss
  uaa/slateCustomizations/source/index.html.md.erb
Labels: documentation, dependencies, ruby, blocked, in_review

#2304 fix: issue 2302
  server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordController.java
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Labels: unscheduled

#2306 Update UAA image reference in k8s to 76.10.0
  k8s/templates/values/image.yml
Labels: unscheduled

#2308 Bump mariadb from 2.7.8 to 2.7.9
  dependencies.gradle
Labels: unscheduled

#2310 fix: Update gem setting to latest slate version (#2257)
  LICENSE
  uaa/build.gradle
  uaa/slate/Gemfile
  uaa/slate/Gemfile.lock
  uaa/slate/config.rb
  uaa/slate/lib/monokai_sublime_slate.rb
  uaa/slate/source/images/logo.png
  uaa/slate/source/layouts/layout.erb
  uaa/slate/source/stylesheets/screen.css.scss
  uaa/slateCustomizations/source/index.html.md.erb
Labels: in progress, accepted
