Repository cloudfoundry/uaa, pull requests merged in 2023-09, with the labels that each got.

#2476 Bump Gradle to 8.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: unscheduled, dependencies, java

#2479 update dependency org.gradle:test-retry-gradle-plugin to v1.5.4
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2478 Bump mariadb from 2.7.9 to 2.7.10
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2480 Bump gradle plugins
  .github/workflows/gradle.yml
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2481 Bump SnakeYaml from 2.0 to 2.2
  dependencies.gradle
Labels: dependencies, java

#2482 update dependency org.gradle:test-retry-gradle-plugin to v1.5.5
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2484 test: Authorization Grant Flow without Redirect URI
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/AuthorizationCodeGrantIntegrationTests.java
Labels: unscheduled

#2485 doc: reason for ignoring library bumps
  .github/dependabot.yml
Labels: unscheduled

#2448 feature: activate PKCE by default in requests to external OIDC providers
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractExternalOAuthIdentityProviderDefinition.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfigurator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfiguratorTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled, in_review

#2488 k8s updates, k8s.io 0.28.1 to 0.28.2
  k8s/go.mod
  k8s/go.sum
Labels: unscheduled, dependencies, go

#2433 refactor: prepare for private_key_jwt in oauth_client_details
  server/src/main/java/org/cloudfoundry/identity/uaa/client/UaaClientDetails.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/UaaClientDetailsUserDetailsService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantClientServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_104__Add_ClientJwtConfig_To_Oauth_Client_Details.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_104__Add_ClientJwtConfig_To_Oauth_Client_Details.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_104__Add_ClientJwtConfig_To_Oauth_Client_Details.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/client/UaaClientDetailsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/InMemoryMultitenantClientServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsServiceTests.java
Labels: unscheduled, in_review

#2491 fix: Flaky test
  uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
Labels: unscheduled

#2439 feature: allow setting SameSite on X-Uaa-Csrf cookie
  server/src/main/java/org/cloudfoundry/identity/uaa/security/web/CookieBasedCsrfTokenRepository.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/CookieBasedCsrfTokenRepositoryTests.java
Labels: unscheduled

#2494 update module github.com/onsi/ginkgo/v2 to v2.12.1
  k8s/go.mod
  k8s/go.sum
Labels: unscheduled

#2497 fix: missing shebang
  scripts/ldap/docker-confirm-ldapquery.sh
  scripts/ldap/mac-ldap-install.sh
Labels: unscheduled

#2449 feature: add persistence support for private_key_jwt client authentication
  docs/UAA-APIs.rst
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/client/ClientDetailsCreation.java
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/client/ClientJwtChangeRequest.java
  model/src/test/java/org/cloudfoundry/identity/uaa/oauth/client/ClientDetailsCreationTest.java
  model/src/test/java/org/cloudfoundry/identity/uaa/oauth/client/ClientJwtChangeRequestTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/audit/AuditEventType.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrap.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsValidator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientJwtConfiguration.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/event/ClientAdminEventPublisher.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/event/ClientJwtChangeEvent.java
  server/src/main/java/org/cloudfoundry/identity/uaa/client/event/ClientJwtFailureEvent.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantClientServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientJwtConfigurationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/event/ClientAdminEventPublisherTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/InMemoryMultitenantClientServices.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsServiceTests.java
  uaa/slateCustomizations/source/index.html.md.erb
  uaa/src/main/webapp/WEB-INF/spring/client-admin-endpoints.xml
  uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientAdminEndpointsIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointsMockMvcTests.java
Labels: in progress

#2461 fix: ClientAdminEndpointsValidator should allow authorization_code with empty secret
  server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsValidator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidatorTests.java
Labels: unscheduled
