Repository cloudfoundry/uaa, pull requests merged in 2023-12, with the labels that each got.

#2634 Bump dependency org.gradle:test-retry-gradle-plugin to v1.5.8
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2616 Check zone id before jdbc access
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioning.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioningTests.java
Labels: unscheduled

#2641 Sonar fix for split
  server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaHttpRequestUtils.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaHttpRequestUtilsTest.java
Labels: unscheduled

#2613 Update documentation for adding SAP IAS as OIDC Provider
  docs/OIDC-Provider-Examples/sap-public-oidc-provider.md
Labels: unscheduled, documentation

#2653 fix: check for existing groups
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneEndpointsTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IdentityZoneEndpointsIntegrationTests.java
Labels: unscheduled

#2656 refactor jackson dependency setting
  dependencies.gradle
Labels: unscheduled

#2618 Limit user creation in zone
  model/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfig.java
  model/src/test/java/org/cloudfoundry/identity/uaa/zone/UserConfigTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfigValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordChangeEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenRevocationEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/UserConfigValidatorTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
Labels: scheduled

#2659 refactor spring version dependency
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2660 upgrade spring security version 5.8.9
  dependencies.gradle
Labels: dependencies, java
