Repository cloudfoundry/uaa, pull requests merged in 2024-06, with the labels that each got.

#2912 Bump Gradle to 8.8
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: unscheduled, dependencies, java

#2882 feature: filter IdP retrival
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
  uaa/slateCustomizations/source/index.html.md.erb
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled

#2919 Documentation for Alias Feature
  docs/UAA-Alias-Entities.md
Labels: unscheduled

#2870 Fix: Zone creation fails when allow list does not contain all default groups
  model/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfig.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioning.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioningTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ScimGroupEndpointsIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
Labels: unscheduled

#2923 Fix issue #2917
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/user/UaaUser.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/OIDCLoginIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java
Labels: unscheduled, bug

#2920 Identity provider key caching behavior configurable
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractExternalOAuthIdentityProviderDefinition.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadataFetcher.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OidcMetadataFetcherTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled

#2918 fix: Support authMethod=none in proxy password grant
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/PasswordGrantAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
Labels: unscheduled

#2931 renovate: : update dependency nokogiri to v1.16.6
  uaa/slate/Gemfile.lock
Labels: unscheduled, dependencies, ruby

#2938 add postgresql 16 tests to github actions
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
Labels: unscheduled

#2940 Fix potential typo in OauthIDPWrapperFactoryBean.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
Labels: unscheduled

#2941 fix: publish an external group auth event only with registered IDPs
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
Labels: unscheduled

#2942 Add 'identity_zone_id' column to indexes for 'alias_zid'
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_109__AliasZid_Indexes.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_109__IdP_AliasZid_IdzId_Index.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_109__AliasZid_Indexes.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_109__IdP_AliasZid_IdzId_Index.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_109__AliasZid_Indexes.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_109__IdP_AliasZid_IdzId_Index.sql
Labels: unscheduled
