Repository cloudfoundry/uaa, pull requests merged in 2024-02, with the labels that each got.

#2706 renovate: update dependency middleman-syntax to v3.4.0
  uaa/slate/Gemfile.lock
Labels: unscheduled, dependencies, ruby

#2707 Bump Gradle to 8.6
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: unscheduled

#2688 fix: check origin of user
  model/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfig.java
  model/src/test/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneTest.java
  model/src/test/resources/org/cloudfoundry/identity/uaa/zone/SampleIdentityZone.json
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
Labels: unscheduled

#2708 Sonar recommendation
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
Labels: unscheduled

#2709 renovate: update dependency nokogiri to v1.16.1
  uaa/slate/Gemfile.lock
Labels: unscheduled, dependencies, ruby

#2713 renovate: update dependency nokogiri to v1.16.2
  uaa/slate/Gemfile.lock
Labels: unscheduled, dependencies, ruby

#2701 feat: clean up unused DB table service_provider
  README.md
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_105__Drop_Table_service_provider.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_105__Drop_Table_service_provider.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_105__Drop_Table_service_provider.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/test/TestUtils.java
Labels: accepted, documentation, performance

#2699 refactor: remove a SAML dependency
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenTestSupport.java
Labels: unscheduled, saml-extension-replacement

#2723 fix: Duplicate Version Numbers in Flyway Migrations for IdP Alias Columns
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_107__Identity_Provider_Add_Alias.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_107__Identity_Provider_Add_Alias.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_107__Identity_Provider_Add_Alias.sql
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/InvitationsIT.java
Labels: unscheduled

#2719 refactor: reduce test dependency on EOL lib
  server/src/test/java/org/cloudfoundry/identity/uaa/security/X509ExpiryCheckingTrustManagerTest.java
Labels: unscheduled

#2725 refactor: split test
  server/src/test/java/org/cloudfoundry/identity/uaa/login/HomeControllerViewTests.java
Labels: unscheduled

#2731 Revert "Ignore failing integration test"
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/InvitationsIT.java
Labels: unscheduled

#2732 refactor: use non-deprecated saml configs in uaa.yml
  scripts/cargo/uaa.yml
Labels: unscheduled

#2702 Fix filter check in ids/Users endpoint
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpointsTests.java
Labels: unscheduled

#2711 fix: reject invalid identity zone
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordChangeEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
Labels: unscheduled

#2721 Maintain tomcat version
  dependencies.gradle
Labels: in progress, accepted, dependencies, java

#2740 renovate: update dependency org.mariadb.jdbc:mariadb-java-client to v2.7.12
  dependencies.gradle
Labels: unscheduled, dependencies, java

#2743 refactor: Remove a use of a constant from opensaml library
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/OIDCLoginIT.java
Labels: unscheduled

#2742 remove more IdP tests
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/saml/SamlAuthenticationMockMvcTests.java
Labels: unscheduled

#2747 avoid NPE
  server/src/main/java/org/cloudfoundry/identity/uaa/logging/LogSanitizerUtil.java
  server/src/test/java/org/cloudfoundry/identity/uaa/logging/LogSanitizerUtilTest.java
Labels: unscheduled

#2718 feat: Use Database availability as indicator for /healthz response
  server/src/main/java/org/cloudfoundry/identity/uaa/health/HealthzEndpoint.java
  server/src/test/java/org/cloudfoundry/identity/uaa/health/HealthzEndpointTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/HealthzEndpointIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/HealthzIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/config/HealthzShouldNotBeProtectedMockMvcTests.java
Labels: unscheduled

#2737 Move IdP Alias Handling to separate Class
  model/src/main/java/org/cloudfoundry/identity/uaa/EntityWithAlias.java
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProvider.java
  model/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/alias/EntityAliasFailedException.java
  server/src/main/java/org/cloudfoundry/identity/uaa/alias/EntityAliasHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderAliasHandler.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdpAliasFailedException.java
  server/src/test/java/org/cloudfoundry/identity/uaa/alias/EntityAliasHandlerValidationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderAliasHandlerEnsureConsistencyTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderAliasHandlerValidationTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdpAliasFailedExceptionTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsAliasMockMvcTests.java
Labels: unscheduled

#2750 Revert "Merge pull request #2718 from cloudfoundry/feat/healthzDataba…
  server/src/main/java/org/cloudfoundry/identity/uaa/health/HealthzEndpoint.java
  server/src/test/java/org/cloudfoundry/identity/uaa/web/HealthzEndpointTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/HealthzEndpointIntegrationTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/HealthzIT.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/config/HealthzShouldNotBeProtectedMockMvcTests.java
Labels: unscheduled

#2751 bump: Pin postgres to latest cve-free patch version
  dependencies.gradle
Labels: unscheduled
