Repository cloudfoundry/uaa, pull requests merged in 2024-03, with the labels that each got.

#2754 fix: UAA 74.5 is vulnerable to CVE-2024-22243
  dependencies.gradle
Labels: unscheduled

#2757 Fix audience type
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtHelper.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/ChainedSignatureVerifierTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/CommonSignerTest.java
Labels: unscheduled

#2760 Sonar fixes
  server/src/main/java/org/cloudfoundry/identity/uaa/logging/LogSanitizerUtil.java
  server/src/main/java/org/cloudfoundry/identity/uaa/logging/SanitizedLogFactory.java
  server/src/test/java/org/cloudfoundry/identity/uaa/logging/SanitizedLogFactoryTest.java
Labels: unscheduled

#2768 Solve sonar bug
  server/src/main/java/org/cloudfoundry/identity/uaa/home/BuildInfo.java
Labels: unscheduled

#2764 more methods for sanitized logging
  server/src/main/java/org/cloudfoundry/identity/uaa/logging/SanitizedLogFactory.java
  server/src/test/java/org/cloudfoundry/identity/uaa/logging/SanitizedLogFactoryTest.java
Labels: unscheduled

#2758 Load jwtClientAuthentication in uaa.yml
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIDPWrapperFactoryBean.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBeanTest.java
Labels: unscheduled

#2770 Fix sonar
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/GeneralIdentityZoneConfigurationValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/GeneralIdentityZoneConfigurationValidatorTests.java
Labels: unscheduled

#2787 update dependency nokogiri to v1.16.3
  uaa/slate/Gemfile.lock
Labels: dependencies, ruby

#2767 Fix uaa start. Prevent exception if encryption section missing
  scripts/cargo/uaa.yml
  server/src/main/java/org/cloudfoundry/identity/uaa/cypto/EncryptionKeyService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/cypto/EncryptionService.java
  server/src/main/resources/spring/login-ui.xml
  server/src/test/java/org/cloudfoundry/identity/uaa/cypto/EncryptionKeyServiceTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/cypto/EncryptionServiceTest.java
Labels: unscheduled, accepted, bug

#2792 fix: saml signatureAlgorithm in AuthnRequest
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/SamlConfigurationBean.java
  uaa/src/main/webapp/WEB-INF/spring/saml-providers.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/BootstrapTests.java
  uaa/src/test/resources/test/config/saml-algorithm-sha256.yml
  uaa/src/test/resources/test/config/saml-algorithm-sha512.yml
Labels: scheduled, in progress, accepted, bug

#2765 Add 'aliasId' and 'aliasZid' Fields to ScimUser
  model/src/main/java/org/cloudfoundry/identity/uaa/scim/ScimUser.java
  model/src/test/java/org/cloudfoundry/identity/uaa/scim/ScimUserTests.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_108__Users_Add_Alias.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_108__Users_Add_Alias.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_108__Users_Add_Alias.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
  uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsMockMvcTests.java
Labels: unscheduled

#2798 Bump Gradle to 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, java

#2797 Cleanup from PR 2765
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordChangeEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenRevocationEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
  uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml
Labels: unscheduled

#2771 Support own key and cert for jwtClientAuthentication
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/beans/ApplicationContextProvider.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthentication.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthenticationTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: in progress, accepted, clarification needed

#2801 fix: gradle test might give false green
  build.gradle
Labels: unscheduled

#2804 Fix flaky test in ScimUserEndpointsMockMvcTests
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsMockMvcTests.java
Labels: unscheduled

#2722 Further Integration Tests for Alias Identity Providers Feature
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsAliasMockMvcTests.java
Labels: unscheduled, in progress, accepted
