Repository cloudfoundry/uaa, pull requests merged in 2024-05, with the labels that each got.

#2845 test-refactoring: remove forked class in tests
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordResetEndpointTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/event/EntityDeletedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/JdbcClientMetadataProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/AutologinAuthenticationManagerTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/util/RandomValueStringGenerator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientAccessTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/ClientRefreshTokenValidityTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenRevocationEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/expression/IsSelfCheckTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/JdbcRevocableTokenProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ChangeEmailEndpointsMockMvcTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/TimeBasedExpiringValueMapTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaTokenUtilsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsServiceTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/IdentityProviderModifiedEventTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/event/ServiceProviderModifiedEventTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/client/ClientMetadataAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/client/ClientMetadataAdminEndpointsMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/invitations/InvitationsEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AuthorizeEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ForcePasswordChangeControllerMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/InvitationsServiceMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/password/PasswordEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/AbstractTokenMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenRevocationEndpointMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/DisableUserManagementSecurityFilterMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneSwitchingFilterMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/ZonesWriteScopeMockMvcTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserLookupMockMvcTests.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserInfoEndpointDocs.java
Labels: unscheduled

#2864 Refactoring: use namedJdbcTemplate bean instead of internal new object
  server/src/main/java/org/cloudfoundry/identity/uaa/client/JdbcQueryableClientDetailsService.java
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/AbstractQueryable.java
  server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/JdbcPagingListFactory.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsService.java
  server/src/main/resources/spring/data-source.xml
  server/src/test/java/org/cloudfoundry/identity/uaa/account/PasswordChangeEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/UaaClientAuthenticationProviderTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authorization/external/LdapGroupMappingAuthorizationManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapMultipleSecretsUpdateTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/ClientAdminBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/client/JdbcClientMetadataProvisioningTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/JdbcQueryableClientDetailsServiceTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/TokenRevocationEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/approval/ApprovalsAdminEndpointsTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimExternalGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimGroupBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrapTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupExternalMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManagerTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioningTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/zone/MultitenantJdbcClientDetailsServiceTests.java
Labels: unscheduled, in progress, accepted

#2871 refactor: Spring Annotations on SamlRelyingPartyRegistrationRepository
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/SamlRelyingPartyRegistrationRepository.java
Labels: unscheduled

#2873 Update tool chain
  k8s/go.mod
Labels: dependencies, go

#2879 refactor: avoid indirect dep from EOL lib spring-security-saml2-core
  server/build.gradle
Labels: unscheduled

#2846 fix: always rotate refresh tokens for public clients
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/refresh/RefreshTokenCreator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/RefreshRotationTest.java
Labels: unscheduled

#2884 fix: /info docs test expectation
  uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointDocs.java
Labels: unscheduled

#2896 2nd alternative fix: allow to change or delete a relyingPartySecret on IdP
  model/src/main/java/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.java
  model/src/main/java/org/cloudfoundry/identity/uaa/constants/ClientAuthentication.java
  model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/TokenConstants.java
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractExternalOAuthIdentityProviderDefinition.java
  model/src/test/java/org/cloudfoundry/identity/uaa/constants/ClientAuthenticationTest.java
  model/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderTest.java
  model/src/test/java/org/cloudfoundry/identity/uaa/provider/OIDCIdentityProviderDefinitionTests.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthIdentityProviderConfigValidator.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthIdentityProviderConfigValidatorTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
Labels: unscheduled

#2891 Sonar refactoring - AbstractUaaEvent class
  server/src/main/java/org/cloudfoundry/identity/uaa/audit/event/AbstractUaaEvent.java
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/event/GroupModifiedEvent.java
  server/src/test/java/org/cloudfoundry/identity/uaa/audit/event/AbstractUaaEventTest.java
Labels: unscheduled

#2890 Sonar refactoring - IdentityProviderEndpoints class
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/EndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsAliasMockMvcTests.java
Labels: unscheduled, accepted

#2868 fix: generate email if it is the empty string on external login
  server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManager.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java
  server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManagerTest.java
Labels: unscheduled, in progress, accepted, in_review

#2903 Add kill_uaa script before run and integrationTest tasks
  build.gradle
Labels: unscheduled

#2910 deps: update dependency org.hsqldb:hsqldb to v2.7.3
  dependencies.gradle
Labels: unscheduled, dependencies, java
