Repository cloudfoundry/uaa, pull requests merged in 2024-07, with the labels that each got.

#2943 Fix Injection of 'aliasEntitiesEnabled' into IdentityProviderEndpoints
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
Labels: unscheduled

#2937 Fix documentation for OpenID connect clientJWT
  uaa/slateCustomizations/source/index.html.md.erb
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointDocs.java
Labels: unscheduled

#2944 Fix Version Handling during Update of User with Alias
  server/src/main/java/org/cloudfoundry/identity/uaa/scim/ScimUserAliasHandler.java
  uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsAliasMockMvcTests.java
Labels: unscheduled

#2952 Refactor: throw an exception if reference in uaa.yml is missing
  server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthentication.java
  server/src/test/java/org/cloudfoundry/identity/uaa/oauth/jwt/JwtClientAuthenticationTest.java
Labels: unscheduled

#2934 Refactor: Load UserConfig as bean
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/IdentityProviderBootstrap.java
  server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/IdentityZoneConfigurationBootstrap.java
  server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
  uaa/src/main/webapp/WEB-INF/spring-servlet.xml
Labels: unscheduled

#2953 Bump Gradle to 8.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies, java

#2932 Add performance index for token resolution
  model/src/main/java/org/cloudfoundry/identity/uaa/provider/SamlIdentityProviderDefinition.java
  model/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfig.java
  model/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderDefinitionTests.java
  model/src/test/java/org/cloudfoundry/identity/uaa/zone/UserConfigTest.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfigurator.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/BootstrapSamlIdentityProviderData.java
  server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderConfigurator.java
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_110__Add_ExternalKey_To_Identity_Provider.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_110__Add_ExternalKey_To_Identity_Provider.sql
  server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_110__Add_ExternalKey_To_Identity_Provider.sql
  server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityProviderBootstrapTest.java
  server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerIT.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthProviderConfiguratorTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/BootstrapSamlIdentityProviderDataTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderConfiguratorTests.java
  server/src/test/java/org/cloudfoundry/identity/uaa/test/TestUtils.java
  uaa/src/main/webapp/WEB-INF/spring-servlet.xml
  uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
Labels: unscheduled

#2968 Dependabot fix for rexml
  uaa/slate/Gemfile.lock
Labels: dependencies, ruby
